version: '3'

services:
  db:
    image: postgres:12.5
    ports:
      - 5433:5432
    volumes:
      - ./.docker-data/postgres-data/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: local_dev
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3005:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5433
      DATABASE_USER: postgres
      DATABASE_PASS: postgres_password
      DATABASE_NAME: local_dev

